# Generated by Django 3.2.13 on 2022-07-06 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220704_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
